<a href="https://colab.research.google.com/github/angarikadas26-lgtm/burnout-prediction-project/blob/main/ArtifactV2_datacleaning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [3]:
!pip install pandas numpy matplotlib seaborn scikit-learn xgboost shap

# IS6611 Applied Research in Business Analytics
# Employee Burnout Prediction
# Group 6


In [4]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [5]:
#read file
df = pd.read_csv(
    '/content/drive/MyDrive/Artefact V2/2024_Eurofound_working_conditions.csv')

/tmp/ipykernel_18258/1709392518.py:2: DtypeWarning: Columns (9,16,43,44,46,48,52,54,55,62,101,102,110,111,127,133,208,212,217,232,243,245,256,258,259,260,288,324,325,334,366,378) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(


In [6]:
#data description
df.head()
df.shape

(36644, 386)

In [7]:
#Step 1-understand (analyze) & clean data
df.info()
df.isnull().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 36644 entries, 0 to 36643
Columns: 386 entries, uniquerespid to calweight
dtypes: float64(7), int64(34), object(345)
memory usage: 107.9+ MB


,0
uniquerespid,0
country_code,0
country,0
language,0
samplingpointid,0
...,...
sector,0
region,0
design_weight,0
gweight,0


In [8]:
#check missing values
missing_values = df.isnull().sum()

missing_values.sort_values(ascending=False)

,0
calweight,0
uniquerespid,0
boss_conf,0
boss_cooperation,0
boss_respect,0
...,...
stratumid,0
householdnumber,0
samplingpointid,0
language,0


In [9]:
#Missing Percentage

missing_percent = (df.isnull().sum() / len(df)) * 100

missing_percent.sort_values(ascending=False)

,0
calweight,0.0
uniquerespid,0.0
boss_conf,0.0
boss_cooperation,0.0
boss_respect,0.0
...,...
stratumid,0.0
householdnumber,0.0
samplingpointid,0.0
language,0.0


In [10]:
#identify data types
df.dtypes.value_counts()

,count
object,345
int64,34
float64,7


In [11]:
#Separate Numerical and Categorical Columns
numerical_cols = df.select_dtypes(include=['int64', 'float64']).columns

categorical_cols = df.select_dtypes(include=['object']).columns

In [12]:
#check duplicate rows
df.duplicated().sum()

np.int64(0)

In [13]:
df.describe()

,country,language,householdnumber,degurba,ISCO_2,ISCO_1,NACE_2,improve_pay_benefits,improve_prospects,improve_workhours,...,time_household,filters_EU27,monthly_income_eur_imp,monthly_income_eur_imp_ppp,hourly_income_eur_imp,income_quintile_country_weighted,occupation,design_weight,gweight,calweight
count,36644.000000,36644.000000,36644.000000,36644.000000,36644.000000,36644.000000,36644.000000,36644.000000,36644.000000,36644.000000,...,36644.000000,36644.000000,36644.000000,36644.000000,36644.000000,36644.000000,36644.000000,36644.000000,36644.000000,36644.000000
mean,17.602309,909.060474,35.186470,1.892779,48.177273,4.563175,581.231334,0.695394,0.264927,0.317842,...,21.036851,0.781056,1823.800829,1963.451699,13.335501,2.903559,15.889013,6045.647118,1.024904,6044.133647
std,10.292970,7649.626488,60.632689,0.830368,24.443581,2.461575,275.497634,0.460247,0.441301,0.465644,...,26.263987,0.413537,1630.787559,1458.498924,24.559638,1.432992,21.921203,10820.448219,0.633671,12872.995011
min,1.000000,2.000000,1.000000,1.000000,1.000000,0.000000,-881.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,8.852571,19.607843,0.070058,1.000000,1.000000,52.521327,0.030000,3.311127
25%,9.000000,10.000000,11.000000,1.000000,25.000000,2.000000,450.000000,0.000000,0.000000,0.000000,...,3.500000,1.000000,788.514769,1052.631579,4.788462,2.000000,2.000000,990.382343,0.582947,773.085404
50%,17.000000,20.000000,21.000000,2.000000,51.000000,5.000000,560.000000,1.000000,0.000000,0.000000,...,14.000000,1.000000,1388.824591,1621.621622,8.695585,3.000000,5.000000,2567.552622,0.948704,2173.920361
75%,26.000000,29.000000,34.000000,3.000000,71.000000,7.000000,850.000000,1.000000,1.000000,1.000000,...,28.000000,1.000000,2440.065341,2500.000000,15.865385,4.000000,30.000000,5137.744517,1.369339,5173.767254
max,35.000000,69657.000000,607.000000,3.000000,96.000000,9.000000,990.000000,1.000000,1.000000,1.000000,...,168.000000,1.000000,68785.252440,59813.262990,1677.621436,5.000000,67.000000,225935.768900,6.612654,392423.299100


In [14]:
#check missing value

missing_table = pd.DataFrame({
    'Missing_Count': df.isnull().sum(),
    'Missing_Percent': missing_percent
})

missing_table.sort_values(
    by='Missing_Percent',
    ascending=False
).head(20)

,Missing_Count,Missing_Percent
calweight,0,0.0
uniquerespid,0,0.0
boss_conf,0,0.0
boss_cooperation,0,0.0
boss_respect,0,0.0
wellbeing,0,0.0
time_household,0,0.0
time_housework,0,0.0
time_elders,0,0.0
time_children,0,0.0


In [15]:
#find suspicious values

for col in df.columns:

    if (df[col].dtype == 'int64') or (df[col].dtype == 'float64'):

        print(col)
        print(df[col].nunique())
        print(df[col].sort_values().unique()[:10])
        print("----------------")

country
35
[ 1  2  3  4  5  6  7  8  9 10]
----------------
language
31
[ 2  3  5  6  7  8  9 10 11 12]
----------------
householdnumber
510
[ 1  2  3  4  5  6  7  8  9 10]
----------------
degurba
3
[1 2 3]
----------------
ISCO_2
43
[ 1  2  3 11 12 13 14 21 22 23]
----------------
ISCO_1
10
[0 1 2 3 4 5 6 7 8 9]
----------------
NACE_2
89
[-881    1    2    3    5    6    7    8    9  100]
----------------
improve_pay_benefits
2
[0 1]
----------------
improve_prospects
2
[0 1]
----------------
improve_workhours
2
[0 1]
----------------
improve_health_safety
2
[0 1]
----------------
improve_social
2
[0 1]
----------------
improve_opportunities
2
[0 1]
----------------
improve_workload
2
[0 1]
----------------
improve_voice
2
[0 1]
----------------
improve_DK
2
[0 1]
----------------
improve_Refused
2
[0 1]
----------------
isced
11
[-999 -998    0    1    2    3    4    5    6    7]
----------------
workstatus
11
[-999 -998    1    2    3    4    5    6    7    8]
----------------
age

In [16]:
# replace suspicious values

df.replace([-999, -998, -881], np.nan, inplace=True)

#re-check missing values again after replacement of suspicious values
(df.isnull().sum().sort_values(ascending=False)).head(20)

,0
NACE_2,160
isced,88
workstatus,33
goodjob_pay,0
goodjob_aut,0
exhaust_emot,0
exhaust_phys,0
eng_timeflies,0
eng_enthusiastic,0
eng_energy,0


In [17]:
#check duplicates
df.duplicated().sum()

np.int64(0)

In [20]:
#before this step, missing values were not replaced, now replacing missing values

#Numerical Columns → Median Imputation

for col in numerical_cols:
    df[col] = df[col].fillna(df[col].median())

#Categorical Columns → Mode Imputation

for col in categorical_cols:
    df[col] = df[col].fillna(df[col].mode()[0])

In [21]:
#Recheck Missing Values

df.isnull().sum().sum()

np.int64(0)

In [22]:
#identfying single value columns

single_value_cols = []

for col in df.columns:

    if df[col].nunique() <= 1:
        single_value_cols.append(col)

single_value_cols

['language_interview']

In [23]:
#checking for extreme outliers

df.describe().T

,count,mean,std,min,25%,50%,75%,max
country,36644.0,17.602309,10.292970,1.000000,9.000000,17.000000,26.000000,35.000000
language,36644.0,909.060474,7649.626488,2.000000,10.000000,20.000000,29.000000,69657.000000
householdnumber,36644.0,35.186470,60.632689,1.000000,11.000000,21.000000,34.000000,607.000000
degurba,36644.0,1.892779,0.830368,1.000000,1.000000,2.000000,3.000000,3.000000
ISCO_2,36644.0,48.177273,24.443581,1.000000,25.000000,51.000000,71.000000,96.000000
ISCO_1,36644.0,4.563175,2.461575,0.000000,2.000000,5.000000,7.000000,9.000000
NACE_2,36644.0,587.523223,257.925027,1.000000,450.000000,560.000000,850.000000,990.000000
improve_pay_benefits,36644.0,0.695394,0.460247,0.000000,0.000000,1.000000,1.000000,1.000000
improve_prospects,36644.0,0.264927,0.441301,0.000000,0.000000,0.000000,1.000000,1.000000
improve_workhours,36644.0,0.317842,0.465644,0.000000,0.000000,0.000000,1.000000,1.000000


In [24]:
#Identify Binary vs Categorical vs Continuous Variables

binary_cols = []
continuous_cols = []
categorical_encoded_cols = []

In [25]:
#Class Balance of Important Variables

df['improve_workload'].value_counts()

,count
improve_workload,
0,27644
1,9000


In [26]:
#SAVE CLEANED VERSION

df.to_csv(
    '/content/drive/MyDrive/Artefact V2/EWCS2024_Cleaned.csv',
    index=False
)